/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "convertidor.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->unidadMedida))
		 return FALSE;
	return TRUE;
}
